version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8.17-management
    ports:
      - 1143:5672
      - 1144:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password

volumes:
  rabbitmq_data: